feed/urls.py
from django.urls import path
from . import views

app_name = 'feed'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:user_id>/profile/', views.profile, name='profile'),
    path('<int:user_id>/unlike', views.unlike, name='unlike'),
    path('<int:image_id>/like/', views.like, name='like'),
    path('leaderboard/', views.LeaderboardView.as_view(), name='poll'),
    path('about/', views.about, name='about'),
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('<int:user_id>/add_image', views.add_image, name='add_image'),
    path('<int:user_id>/upload_file', views.upload_file, name='upload_file'),
]

photosite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('feed.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import User
from django.conf import settings
from django.forms import ModelForm

class Collection(models.Model):
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField('Date created')

    def was_created_recently(self):
        return self.created_at >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.name

# Create a foreign key to form a relationship between User and Image objects
# e.g. each Image is related to a single User (if not initially at some point once 'liked')
class Image(models.Model):
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    src = models.CharField(max_length=255, default="")
    alt = models.CharField(max_length=255)
    created_at = models.DateTimeField('image created')
    votes = models.IntegerField(default=0)
    data = models.ImageField(upload_to='images', default="")

    def was_created_recently(self):
        return self.created_at >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return "{t} <User: {u}> <Collection: {c}>".format(t=self.title, u=self.user.username, c=self.collection.name)

feed/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db import models

# Form model - using built-in UserCreationForm registration form
class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

# Uploading Files Form
class UploadFile(models.Model):
	title = models.CharField(max_length=255)
	file = models.FileField(upload_to='files')

class ModelFormWithFileField(ModelForm):
	class Meta:
		model = UploadFile
		fields = ['title', 'file']

# Uploading Images Form
class UploadImage(models.Model):
	title = models.CharField(max_length=255)
	alt = models.CharField(max_length=255)
	file = models.ImageField(upload_to='images')

class ModelFormWithImageField(ModelForm):
	class Meta:
		model = UploadImage
		fields = ['title', 'alt', 'file']

feed/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Collection, Image
from django.contrib.auth.models import User
from django.utils import timezone
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import NewUserForm, ModelFormWithFileField, ModelFormWithImageField
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.conf import settings
from os import getcwd, path
from pandas import read_csv
from unicodedata import normalize
from unidecode import unidecode

cwd = getcwd()

# Setup generic views
class IndexView(generic.ListView):
    template_name = 'feed/base_index.html'
    context_object_name = 'latest_image_feed'
    c = Collection.objects.get(name='main_feed')
    def get_queryset(self):
        """Return images from the 'main_feed' collection."""
        i = Image.objects.filter(collection=self.c.id)
        return i[::-1]

# view the image on its own page in more detail
# feed/<int id: id>/
# feed/image-name
class DetailView(generic.DetailView):
    model = Image
    template_name = 'feed/base_detail.html'

class AboutView(generic.DetailView):
    model = Image
    template_name = 'feed/base_about.html'

class ResultsView(generic.ListView):
    model = Collection
    template_name = 'feed/base_results.html'
    context_object_name = 'user_liked'
    
    def get_queryset(self):
        u = User.objects.get(pk=1)
        get_all = u.image_set.order_by('-votes')
        return get_all

class LeaderboardView(generic.ListView):
    model = Collection
    template_name = 'feed/base_poll.html'
    context_object_name = 'leaderboard'

    def get_queryset(self):
        # get the main_feed (collection with id/primary key equaling 1)
        c = Collection.objects.get(pk=1)
        get_all = c.image_set.order_by("-votes")
        return get_all

def about(request):
    return render(request, 'feed/base_about.html')

def profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)

    if user.id != request.user.id:
        # raise Http404("You don't have permission to access this page. User is not authenticated")
        return redirect('feed:index')
    try:
        c = Collection.objects.get(name="{u}_{uid}".format(u=user.username, uid=user_id))
    except Collection.DoesNotExist:
        c = Collection(name="{u}_{i}".format(u=user.username, i=user.id), created_at=timezone.now())
        c.save()

    liked = user.image_set.filter(collection=c.id)

    return render(request, 'feed/base_profile.html', {
        'liked': liked[::-1],
        'likedNum': len(liked),
        'uid': request.user.id
    })

def likeHelper(coll, selected_choice, u):
    coll.image_set.create(
        collection=coll,
        user=u,
        title=selected_choice.title,
        alt=selected_choice.alt,
        src=selected_choice.src or "",
        created_at=selected_choice.created_at,
        votes=selected_choice.votes,
        data=selected_choice.data
        )
    coll.save()

def like(request, image_id):
    image = get_object_or_404(Image, pk=image_id)
    if request.user.is_authenticated == False:
        return redirect('feed:login')

    u = get_object_or_404(User, pk=request.user.id)
    coll_exists = ""

    try:
        selected_choice = Image.objects.get(pk=request.POST['option'])
        coll_exists = Collection.objects.get(name="{u}_{i}".format(u=u.username, i=u.id))
        likeHelper(coll_exists, selected_choice, u)
    except (Collection.DoesNotExist, KeyError, Image.DoesNotExist) as e:
        coll_exists = Collection(name="{u}_{i}".format(u=u.username, i=u.id), created_at=timezone.now())
        coll_exists.save()
        likeHelper(coll_exists, selected_choice, u)
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('feed:profile', args=(u.id,)))
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('feed:profile', args=(u.id,)))
    

def register(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
            # After user successfully is registered, login
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect('feed:index')
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render(request=request, template_name="feed/base_register.html", context={"register_form":form})

def login_user(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect('feed:index')
            else:
                messages.error(request,"Invalid username or password.")
        else:
            messages.error(request,"Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="feed/base_login.html", context={"login_form":form})

def logout_user(request):
	logout(request)
	messages.info(request, "You have successfully logged out.") 
	return redirect("feed:index")

def unlike(request, user_id):
    u = get_object_or_404(User, pk=user_id)
    cname = "{u}_{uid}".format(u=u.username, uid=u.id)
    img_id = request.POST['image']

    try:
        coll = Collection.objects.get(name=cname)
        cimg = coll.image_set.get(id=img_id)
        # delete the image from the users collection
        cimg.delete()
        # and decrement the votes counter for that image
        # in the main feed to reflect in the leaderboards
        main_feed = Collection.objects.get(pk=1)
        img = main_feed.image_set.get(title=cimg.title)
        img.votes -= 1
        if img.votes < 0:
            img.votes = 0
        img.save()
    except (KeyError, Collection.DoesNotExist, Image.DoesNotExist) as e:
        print("Collection or Image does not exist!", e)

    return HttpResponseRedirect(reverse('feed:profile', args=(u.id,)))

def add_image(request, user_id):
    u = get_object_or_404(User, pk=user_id)
    c = Collection.objects.get(pk=1)
    title = request.POST['title']
    alt = request.POST['alt']

    form = ModelFormWithImageField(request.POST, request.FILES)
    path = "{path}{filename}".format(path="images/", filename=request.FILES['file'])
    filelist = request.FILES.getlist('file')

    if form.is_valid():
        if (len(filelist) == 1):
            form.save()
            try:
                path = unidecode(path)
                i = Image(collection=c, user=u, title=title, alt=alt, src="", created_at=timezone.now(), votes=0, data=path)
                i.save()
            except FileNotFoundError as e:
                print("Uploaded filename differs from the image source in template", e)
        else:
            for f in filelist:
                path = "{path}{filename}".format(path="images/", filename=f.name)
                fr = ModelFormWithImageField(request.POST, request.FILES)
                if fr.is_valid():
                    try:
                        obj = fr.save(commit=False)
                        obj.file = f
                        obj.save()
                        path = unidecode(path)
                        i = Image(collection=c, user=u, title=title, alt=alt, src="", created_at=timezone.now(), votes=0, data=path)
                        i.save()
                    except FileNotFoundError as e:
                        print("Uploaded filename differs from the image source in template", e)
    else:
        form = ModelFormWithImageField()
    
    return HttpResponseRedirect(reverse('feed:profile', args=(user_id,)))

# Not needed as I'm using Models for ImageField and FileField uploads
def handle_uploaded_file(file):
    """Write uploaded file to a new file in chunks."""
    with open("media/sample.txt", 'wb+') as dest:
        for chunk in file.chunks():
            dest.write(chunk)

def upload_file(request, user_id):
    """Handle user uploaded CSV files."""
    if request.method == 'POST':
        u = get_object_or_404(User, pk=user_id)
        c = Collection.objects.get(pk=1)
        form = ModelFormWithFileField(request.POST, request.FILES)
       
        if form.is_valid():
            # file is saved
            form.save()

            # Todo - Handle duplicate file uploads which get 
            # hashed by django like somefile_D7hvhsj.png, turns out its harder
            # than it looks to get that UploadFile object instance with hashed name
            # maybe just overwrite existing files for now?

            df = read_csv("./media/files/{f}".format(f=request.FILES['file']))
            imglist = []
            for item in df.itertuples():
                #path = "{path}{file}".format(path="images/", file=item[2].strip())
                imglist.append(
                    Image(
                        user=u, 
                        collection=c, 
                        title=item[1].strip(),
                        src=item[2].strip(),
                        alt=item[3].strip(), 
                        created_at=timezone.now(), 
                        votes=0, 
                        data=""
                    )
                )
            # do a massive insert query to Image
            bulkQuery = Image.objects.bulk_create(imglist)
            return HttpResponseRedirect(reverse('feed:profile', args=(user_id,)))

feed/templates/feed/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'feed/css/style.css' %}">
</head>
<body>
    <header class="top-header">
        <nav class="main-nav">
            <a href="{% url 'feed:index' %}" class="home-logo"><span>📷</span></a>
            <ul>
                <li><a href="{% url 'feed:index' %}">Feed</a></li>
                <li><a href="{% url 'feed:about' %}">About</a></li>
                <li><a href="{% url 'feed:poll' %}">Leaderboard</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'feed:profile' user.id %}">Profile</a></li>
                {% if user.is_superuser %}
                <li><a href="/admin">Dashboard</a></li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'feed:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'feed:register' %}">Sign up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'feed:login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block header %}{% endblock %}
    <main>
    {% block main %}{% endblock %}
    </main>
    <footer>
        <p>&copy; 2021 Tanner Dolby. Built with <a href="https://docs.djangoproject.com/en/3.2/">Django</a></p>
    </footer>
</body>
</html>

feed/templates/feed/base_about.html
{% extends "feed/base.html" %}
{% load static %}
{% block title %}About Us | Django Photo Feed{% endblock %}
{% block  header %}<h1 class="hero-h">About Our Team</h1>{% endblock %}
{% block main %}
<div class="about-wrap">
<p class="about-p">Thanks for the interest. We open source our images from <a href="https://pexels.com">pexels.com</a> amongst other user uploaded content. We aim to provide a user friendly image viewing experience where you can accumulate a collection of liked photos as our site continues to grow and the feed gets more robust.</p>
<h3 class="about-h3">Reach out</h3>
<p class="about-p">If you need to contact us, the team will be available to answer your questions or concerns from 8am-4:30pm (PST) M-F. If it is an emergency, and you must reach us sooner. Feel free to drop an email to <i>djphotos@help.com</i> and we will get back to you within 24-48hrs.
<ul>
    <li>By Phone: (555)-555-5555</li>
    <li>By Email: djphotos@gmail.com</li>
</ul>
</div>
{% endblock %}

feed/templates/feed/base_detail.html
{% extends "feed/base.html" %}
{% load static %}
{% block title %}{{ image.title }} | Django Photo Feed{% endblock %}
{% block main %}
{% if image.data.name == "" %}
<a href="{% url 'feed:detail' image.pk %}">
    <img class="img-solo" src="{{ image.src }}" alt="{{ image.alt }}" loading="lazy" width="1024" height="640" />
</a>
{% else %}
<a href="{% url 'feed:detail' image.pk %}">
    <img class="img-solo" src="{{ MEDIA_URL }}{{ image.data.name }}" alt="{{ image.alt }}" loading="lazy" width="1024" height="640" />
</a>
{% endif %}
<div class="detail-wrap">
<div class="row">
<h1>{{ image.title }}</h1>
<form action="{% url 'feed:like' image.id %}" method="post">
    {% csrf_token %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <input type="text" style="display: none;" name="option" value="{{ image.id }}">
    <button class="like-btn" type="submit">Like photo <svg id="color" enable-background="new 0 0 24 24" height="24px" width="24px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="m11.466 22.776c.141.144.333.224.534.224s.393-.08.534-.224l9.594-9.721c4.001-4.053 1.158-11.055-4.532-11.055-3.417 0-4.985 2.511-5.596 2.98-.614-.471-2.172-2.98-5.596-2.98-5.672 0-8.55 6.984-4.531 11.055z" fill="#f44336"/></svg></button>
</form>
</div>
<p>{{ image.alt }}</p>
<p>Popularity: {{ image.votes }} likes</p>
</div>
{% endblock %}

feed/templates/feed/base_index.html
{% extends "feed/base.html" %}
{% load static %}
{% block title %}Home | Django Photo Feed{% endblock %}
{% block  header %}<h1 class="hero-h">Django Photo Feed</h1>{% endblock %}
{% block main %}
<p class="hero-p">Welcome! Browse from the main gallery feed below. Stock images that populate the feed are from <a href="https://pexels.com">Pexels</a>. Click on an image to view more details about it. Add the image to your "liked" colletion by clicking the "like" button. Login to view your profile and corresponding liked collection.</p>
{% if latest_image_feed %}
<ul class="image__feed">
    {% for image in latest_image_feed %}
    <li>
        {% if image.data.name == "" %}
        <a href="{% url 'feed:detail' image.pk %}">
            <img src="{{ image.src }}" alt="{{ image.alt }}" loading="lazy" width="400px" height="400px" />
        </a>
        {% else %}
        <a href="{% url 'feed:detail' image.pk %}">
            <img src="{{ MEDIA_URL }}{{ image.data.name }}" alt="{{ image.alt }}" loading="lazy" width="400px" height="400px" />
        </a>
        {% endif %}
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

feed/templates/feed/base_login.html
{% extends "feed/base.html" %}
{% block title %}Login | Django Photo Feed{% endblock %}

{% block main %}      
<div class="login-container">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form }}
    <button class="btn" type="submit">Login</button>
  </form>
  <p>Don't have an account? <a href="{% url 'feed:register' %}">Create an account</a></p>
</div>

{% endblock %}

feed/templates/feed/base_poll.html
{% extends "feed/base.html" %}
{% load static %}
{% block title %}Leaderboards | Django Photo Feed{% endblock %}
{% block  header %}
<div class="poll-hero">
<h1 class="hero-h">Liked Leaderboards</h1>
<p class="hero-p">The table below contains current vote tallies for all images in the feed. This 'main_feed' is populated from the database with hand picked images. Each user has their own collection created in the form of {username}_{id}. If you want to view only your accounts liked collection without community votes, head over to your profile.</p>
</div>
{% endblock %}
{% block main %}
<table>
    <thead>
        <tr>
            <th>Place</th>
            <th>Image</th>
            <th>Likes</th>
        </tr>
    </thead>
    <tbody>
        {% for img in leaderboard %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'feed:detail' img.id %}">{{ img.title }}</a></td>
            <td>{{ img.votes }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

feed/templates/feed/base_profile.html
{% extends "feed/base.html" %}
{% load static %}
{% block title %}{{ user.username }}'s Profile | Django Photo Feed{% endblock %}
{% block  header %}
<div class="profile-block">
    <div class="wrap-profile">
        <img class="profile-avatar" src="{% static 'feed/svg/user.svg' %}" alt="default user profile picture" />
        <h1>{{ user.username }}'s Profile</h1>
        <ul>
            <li>Account created on: {{ user.date_joined }}</li>
            <li>Username: {{ user.username }}</li>
            <li>Email: {{ user.email }}</li>
            <li>Is Admin: {{ user.is_superuser }}</li>
        </ul>
    </div>
</div>
{% endblock %}
{% block main %}
{% if user.is_superuser %}
<h2 class="image-operations">Add Images To The Feed</h2>

<h3>Upload an Image from the filesystem</h3>
<form class="image-form" action="{% url 'feed:add_image' user.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <label for="title">Image Title</label>
    <input type="text" name="title">
    <label for="alt">Alt text</label>
    <input type="text" name="alt">
    <label for="file">Upload a image (jpeg, png, webp)</label>
    <input type="file" multiple accept="image/*, .pdf" name="file">
    <button type="submit">Submit</button>
</form>

<h3>Upload a CSV file to insert multiple images at once</h3>
<form class="csv-form" action="{% url 'feed:upload_file' user.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <label for="title">Upload Description (ie adding images to main feed)</label>
    <input type="text" name="title">
    <label for="file">Upload file</label>
    <input type="file" accept=".csv" name="file">
    <button type="submit">Submit</button>
</form>

{% endif %}
<div class="profile-container">
<h2>Liked Collection - {{ likedNum }} photos</h2>
{% if likedNum == 0 %}
<a href="{% url 'feed:index' %}">Add images to your collection</a>
{% endif %}
{% if user.is_authenticated %}
<ul class="profile-liked">
    {% for image in liked %}
    <li>
        <div>
            {% if image.data.name == "" %}
            <a href="{% url 'feed:detail' image.pk %}">
                <img src="{{ image.src }}" alt="{{ image.alt }}" loading="lazy" width="300px" height="300px" />
            </a>
            {% else %}
            <a href="{% url 'feed:detail' image.pk %}">
                <img src="{{ MEDIA_URL }}{{ image.data.name }}" alt="{{ image.alt }}" loading="lazy" width="300px" height="300px" />
            </a>
            {% endif %}
            <p>{{ image.title }}</p>
            <p>Liked on {{ image.created_at }}</p>
            <details>
            <summary>Options</summary>
            <form class="remove-form" action="{% url 'feed:unlike' user.id %}" method="post">
                {% csrf_token %}
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                <input type="text" style="display: none;" name="image" value="{{ image.id }}">
                <button class="like-btn" type="submit">Remove</button>
            </form>
            </details>
        </div>
    </li>
    {% endfor %}
</ul>
</div>
{% endif %}
{% endblock %}

feed/templates/feed/base_register.html
{% extends "feed/base.html" %}
{% block title %}Register | Django Photo Feed{% endblock %}
{% block main %}         

<div class="register-container">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		<label for="id_username">Username:</label><input type="text" name="username" maxlength="150" autofocus="" required="" id="id_username">
		<label for="id_email">Email:</label><input type="email" name="email" required="" id="id_email">
		<label for="id_password1">Password:</label><input type="password" name="password1" autocomplete="new-password" required="" id="id_password1">
		<label for="id_password2">Password confirmation:</label><input type="password" name="password2" autocomplete="new-password" required="" id="id_password2">
		<button class="btn" type="submit">Register</button>
	</form>
	<p>If you already have an account, <a href="{% url 'feed:login' %}">login</a> instead.</p>
</div>

{% endblock %}